[package]
name = "rsa_rng"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
crypto-bigint = { version = "0.6.1", features = ["alloc"] }
crypto-primes = "0.6.2"
rand = { version = "0.8.5"}
